// frontend/src/app/components/user-profile/user-profile.component.ts
import { Component, Input } from '@angular/core';
import { MatCardModule } from '@angular/material/card';
import { Comment } from '../../models/comment.model';
import { BASE_URL } from '../../environment/environment';
import { CookieService } from 'ngx-cookie-service';
import { decodeJwtToken } from '../../utils/decode-jwt-token';
import { Subscription } from 'rxjs';
import { PosterInfo } from '../../models/poster-info.model';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-user-profile',
  standalone: true,
  imports: [CommonModule, MatCardModule],
  templateUrl: './user-profile.component.html',
  styleUrl: './user-profile.component.css',
})
export class UserProfileComponent {
  title = '';
  subtitle = '';
  avatar_image = '';
  BASE_URL = BASE_URL;
  @Input() commenter_info!: Comment;
  @Input() action = '';
  @Input() posterInfo!: PosterInfo;

  constructor(private cookieService: CookieService) {}

  ngOnInit() {
    if (this.action == 'feed') {
      this.getPostUserInfo();
    } else if (this.action == 'comment') {
      this.getCommentUserInfo();
    } else {
      const token = this.cookieService.get('jwt');
      const user = decodeJwtToken(token).user;
      this.title = user.username;
      this.avatar_image = BASE_URL + 'uploads/' + user.image;
    }
  }

  getPostUserInfo() {
    this.avatar_image = BASE_URL + 'uploads/' + this.posterInfo.image;
    this.title = this.posterInfo.username;
  }

  getCommentUserInfo() {
    this.avatar_image =
      BASE_URL + 'uploads/' + this.commenter_info.commenterInfo.image;
    this.title = this.commenter_info.commenterInfo.username;
    this.subtitle = this.commenter_info.text;
  }
}

<!-- <mat-card-header>
    <div mat-card-avatar class="avatar">
        <img mat-card-image [src]="avatar_image">
    </div>
    <mat-card-title class="profile_title">{{title}}</mat-card-title>
    <mat-card-subtitle class="profile_subtitle">{{subtitle}}</mat-card-subtitle>
</mat-card-header> -->
<mat-card-header class="user-profile-header">
    <img class="avatar" mat-card-image [src]="avatar_image" alt="User Avatar">
    <div class="user-info">
        <mat-card-title class="profile_title">{{title}}</mat-card-title>
        <mat-card-subtitle class="profile_subtitle">{{subtitle}}</mat-card-subtitle>
    </div>
</mat-card-header>

// frontend-with-react/social-media-feed/src/pages/common/UserProfile.js
import React, { useState, useEffect } from 'react';
import PropTypes from 'prop-types';
import { environment } from '../../config/environment'; // Assuming you have this in your environment
import { useUser } from '../../hooks/useUser'; // Use the useUser hook to get the user info
import '../../styles/css/UserProfile.css';

const UserProfile = ({ commenterInfo, action, posterInfo }) => {
  const { user } = useUser(); // Using the useUser hook to get the logged-in user
  const [title, setTitle] = useState('');
  const [subtitle, setSubtitle] = useState('');
  const [avatarImage, setAvatarImage] = useState('');

  useEffect(() => {
    if (action === 'feed') {
      getPostUserInfo();
    } else if (action === 'comment') {
      getCommentUserInfo();
    } else if (user) {
      setTitle(user.username); // Using the user object from context
      setAvatarImage(`${environment.BASE_URL}uploads/${user.image}`);
    }
  }, [action, commenterInfo, posterInfo, user]);

  const getPostUserInfo = () => {
    setAvatarImage(`${environment.BASE_URL}uploads/${posterInfo.image}`);
    setTitle(posterInfo.username);
  };

  const getCommentUserInfo = () => {
    setAvatarImage(
      `${environment.BASE_URL}uploads/${commenterInfo.commenterInfo.image}`
    );
    setTitle(commenterInfo.commenterInfo.username);
    setSubtitle(commenterInfo.text);
  };

  if (!user) {
    return <div>Loading...</div>; // Render a loading state until user data is available
  }

  return (
    <div className="user-profile-header">
      <img
        src={avatarImage}
        alt="User Avatar"
        className="avatar"
        aria-label="avatar image"
      />
      <div className="user-info">
        <h2 className="profile-title" aria-label="Profile Name">
          {title}
        </h2>
        {subtitle && (
          <h3 className="profile-subtitle" aria-label="Profile description">
            {subtitle}
          </h3>
        )}
      </div>
    </div>
  );
};

UserProfile.propTypes = {
  commenterInfo: PropTypes.shape({
    commenterInfo: PropTypes.shape({
      image: PropTypes.string.isRequired,
      username: PropTypes.string.isRequired,
    }),
    text: PropTypes.string.isRequired,
  }),
  action: PropTypes.string,
  posterInfo: PropTypes.shape({
    image: PropTypes.string.isRequired,
    username: PropTypes.string.isRequired,
  }),
};

export default UserProfile;
